---
ID: "60d554e6-cfca-46e9-8fcb-a6acd52f419a"
Parent: "9eee45eb-e887-4d28-8705-8957b69f387e"
Template: "a5aaca0d-77c0-4741-ab77-211cfbdd9e5c"
Path: /sitecore/content/Applications/Content Editor/Editors/Sitecore Cognitive Services/Intelligent Search/Sync Applications
DB: core
SharedFields:
- ID: "6f371c74-5bd5-4ebd-b10a-fc54716021ae"
  Hint: Url
  Value: /SitecoreCognitiveServices/IntelligentSearch/SyncApplications
- ID: "ab8d0102-91f3-43b6-90aa-5a0641dc8521"
  Hint: Icon
  Value: Office/32x32/arrow_circle2.png
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Brug
  - ID: "f7c42332-728e-48b7-bb3c-0d6883e45628"
    Hint: Header
    Value: Brug
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T103529Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Benutzung
  - ID: "f7c42332-728e-48b7-bb3c-0d6883e45628"
    Hint: Header
    Value: Benutzung
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T104039Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Fields:
  - ID: "f7c42332-728e-48b7-bb3c-0d6883e45628"
    Hint: Header
    Value: Setup
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20061208T185950Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 使用量
  - ID: "f7c42332-728e-48b7-bb3c-0d6883e45628"
    Hint: Header
    Value: 使用量
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T104426Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
