---
ID: "782a4ba2-5560-47db-aa83-d819e280b6db"
Parent: "b7f698e1-d181-48d7-bf40-4a436d5f8aca"
Template: "1db34c92-03b0-4475-9a39-da14e4d9d8fc"
Path: /sitecore/content/Applications/Content Editor/Ribbons/Chunks/Intelligent Search/Backup Application
DB: core
SharedFields:
- ID: "d47ed548-84d5-4622-9886-5cc164727507"
  Hint: Icon
  Value: Office/32x32/box_into.png
- ID: "dbbf9ee3-c30e-4456-a81f-ed8c2e8df91b"
  Hint: Click
  Value: "cognitive:backupapplication"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170106T133800Z
    - ID: "4df6da21-e745-444c-956e-1d4a96ab8821"
      Hint: Header
      Value: Backup Application
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a1a31a93-c4a0-4396-b629-67c33001a3cf"
      Hint: Tooltip
      Value: Backup Application
