---
ID: "85e24d56-f579-4114-a110-056d8b2c8e87"
Parent: "3b23ffaf-37de-4780-ae22-e32fcfa82343"
Template: "3b23ffaf-37de-4780-ae22-e32fcfa82343"
Path: /sitecore/templates/Sitecore Cognitive Services/Features/Intelligent Search/Intelligent Search Settings/__Standard Values
DB: master
SharedFields:
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T194456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
