---
ID: "98290b94-6189-4142-8c35-d21f42273edd"
Parent: "3b23ffaf-37de-4780-ae22-e32fcfa82343"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Sitecore Cognitive Services/Features/Intelligent Search/Intelligent Search Settings/Intelligent Search Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181123T164500Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
